# General Jekyll Config
highlighter: rouge
url: http://robotdisco.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, vendor]
kramdown:
  input: GFM
timezone: America/Toronto
